name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: |
#         cd action-a && docker build . --file Dockerfile --tag hello-docker:$(date +%s)
#         echo ${{ github.ref }}
#         echo git rev-parse --short HEAD

    - name: Create Release Name
      id: vars
      shell: bash
      run: |
        echo $GITHUB_SHA
        git rev-parse --short "$GITHUB_SHA"
        echo "::set-output name=sha_short::$(git rev-parse --short "$GITHUB_SHA")"
        
    - name: Create Pre-Release
      id: create_pre_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.vars.outputs.sha_short }}
        release_name: Release 0.0.1-${{ steps.vars.outputs.sha_short }}
        body: |
          Alpha Release for testing only
        draft: false
        prerelease: true    
